In [11]:
from numpy import arange
x = arange(1, 11)
y = (4*x - 5)/7
print (x, y, sep="\n")

[ 1  2  3  4  5  6  7  8  9 10]
[-0.14285714  0.42857143  1.          1.57142857  2.14285714  2.71428571
  3.28571429  3.85714286  4.42857143  5.        ]


In [19]:
import random
x1 = random.choice(x)
y1 = y[x1-1]
print(x1, y1)

6 2.7142857142857144


In [20]:
x2 = random.choice(x)
y2 = y[x2-1]
print(x2, y2)

8 3.857142857142857


In [21]:
x3 = 13.5
y3 = y1 + (x3 - x1)/(x2 - x1)*(y2 - y1)
print(x3, y3)

13.5 7.0


In [23]:
a = arange(1, 11)
b = a**2
print(a, b, sep="\n")

[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]


In [24]:
import random
a1 = random.choice(a)
b1 = b[a1-1]
print(a1, b1)

2 4


In [28]:
a2 = random.choice(a)
b2 = b[a2-1]
print(a2, b2)

8 64


In [30]:
a3 = 15
a3_square = a3**2
b3 = b1 + (a3 - a1)/(a2 - a1)*(b2 - b1)
print(a3, b3, a3_square)

15 44.16666666666667 225
